#ifndef PLATFORM_CONSTANTS_H
#define PLATFORM_CONSTANTS_H

#define SYSCLK_FREQ_MHZ 48U
#define SYSCLK_FREQ_HZ (SYSCLK_FREQ_MHZ * 1000000U)

#define USART USART1
#define RCC_USART RCC_USART1
#define RCC_UART_GPIO RCC_GPIOA
#define PORT_UART GPIOA
#define PIN_UART_TX GPIO9
#define PIN_UART_RX GPIO10

#define PORT_ADC GPIOB
#define RCC_ADC_GPIO RCC_GPIOB
#define PIN_DUTY GPIO0
#define PIN_TEMPO GPIO1
#define ADC_CHANNEL_DUTY 8
#define ADC_CHANNEL_TEMPO 9
#define RCC_ADC_TIMER RCC_TIM3
#define ADC_TIMER TIM3
#define ADC_TIMER_TRIGGER ADC_CFGR1_EXTSEL_TIM3_TRGO
#define ADC_TRIGGER_RATE_HZ 1000

#define PORT_STATUS_LED GPIOA
#define PIN_STATUS_LED GPIO15
#define RCC_STATUS_LED_GPIO RCC_GPIOA
#define PORT_LEDS GPIOB
#define PIN_LEDS GPIO3
#define LEDS_TIMER TIM2
#define LEDS_TIM_OC TIM_OC2
#define LEDS_GPIO_AF GPIO_AF2
#define RCC_LEDS_GPIO RCC_GPIOB
#define RCC_LEDS_TIMER RCC_TIM2
// TODO: calculate this based on led protocol
#define LED_FREQ_HZ 10000

#define RCC_SEQCLKOUT_GPIO RCC_GPIOA
#define RCC_SEQCLKOUT_TIMER RCC_TIM1
#define PORT_SEQCLKOUT GPIOA
#define PIN_SEQCLKOUT GPIO11
#define SEQCLKOUT_TIMER TIM1
#define SEQCLKOUT_TIM_OC TIM_OC4
#define SEQCLKOUT_GPIO_AF GPIO_AF2
#define SEQCLKOUT_FREQ_HZ 1000
#define TIMER_PRESCALER 2000

#endif // PLATFORM_CONSTANTS_H
